### ISSUE TITLE
Request for new Meetup to be added to event stream

### ISSUE THREAD

**Issue by camow7** [newwwie/newwwie.com#10]
**Meetup Group URL:** [https://www.meetup.com/Blast-Furnace/ ](https://www.meetup.com/Blast-Furnace/ )
**Meetup relevance:** Local interactive meetup where members can learn to code or mingle with experienced programmers.

**Comment by camow7** [comment]
I also put a pull request here with all the info for the meetup but it seemed out of date? https://github.com/newwwie/events-meetups

**Comment by domsammut** [comment]
Hey @camow7 

It appears Blast Furnace is already included in the events stream: https://github.com/newwwie/newwwie.com/blob/master/src/js/events/Meetup.js#L51

I just double checked on the Meetup site to confirm that it is indeed the correct id. There are no upcoming events for the group, so once the next event is created it should appear in the stream (the events stream only 20 upcoming events from now).

I'm going to mark this issue as closed as the pull request on the other repo has also been merged :)

Please don't hesitate to re-open/create another issue if there's anything else!

Cheers
Dom
