### ISSUE TITLE
Convert fetch-events to Typescript too

### ISSUE THREAD

**Issue by neozenith** [newwwie/newwwie.com#121]
After converting the main website to Typescript in #117 there is still a helper script in plain NodeJS that needs to be converted.

Successfully closing this issue would mean the following works:

`package.json`
```diff
{
  "scripts": {
-    "fetchEvents": "node ./fetch-events/index.js",
+    "fetchEvents": "ts-node ./fetch-events/index.ts",
  },
}
```

**Comment by OsamaImadi** [comment]
@neozenith can I work on this?
