### ISSUE TITLE
Render Markdown for Event Descriptions

### ISSUE THREAD

**Issue by neozenith** [newwwie/newwwie.com#126]
Meetup has enabled rich descriptions which look like a markdown format. Could we get this content rendered from MD format to HTML format?
<img width="651" alt="Screenshot 2024-06-27 at 5 45 16 AM" src="https://github.com/newwwie/newwwie.com/assets/159722/fe86c55d-f13c-4823-9505-d09a92b820f7">

**Comment by ParthJohri** [comment]
Hi @neozenith,

I have some suggestions for this issue:-

1. We can create a function to parse the markdown text and use regex expression to change popular markdown to html, however that could be a cumbersome person.

2. Using an external api like https://apyhub.com/utility/md-content-html to fetch the html formatted data, but this would come around costly if used for a number of requests.

3. Creating our custom backend api on python or NodeJs use libraries to convert the md file to html file.

Would like to discuss as to what approach would be more appropriate over here?

**Comment by neozenith** [comment]
The content, we fetch daily when we do static site builds and the final product is already known. So calling out to APIs is not approproate.

I would prefer looking at prior art as a NodeJS library such as the following that could be incorporated into a build step. 

- https://github.com/showdownjs/showdown
- https://github.com/markedjs/marked

**Comment by ParthJohri** [comment]
Greetings @neozenith,

I made use of showdown Nodejs library to format the text, here is the screenshot with the result, if this looks good, I can create a PR for it.
![Screenshot 2024-07-22 at 16 03 27](https://github.com/user-attachments/assets/c10f6871-2ecd-4b2c-b4b4-89f80f987a4f)

**Comment by neozenith** [comment]
Yeah looks great. Feel free to open a PR
