### ISSUE TITLE
Event list displaying blank

### ISSUE THREAD

**Issue by clbaita** [newwwie/newwwie.com#61]
When I visited the website and checked the events list, it seemed to display no events. The fetchEvents action is correctly populating the list and that data is contained within the script for the website. There was a strange error in the console and it seemed to be coming from webpack. 

I was able to reproduce this locally by running the exact commands in the workflow.

It seems that one of the plugins, namely babel-minify-webpack-plugin, was deprecated and that functionally build into webpack itself. Yarn somehow hid this issue and still built successfully, whereas npm errored out.

I have removed the deprecated package and updated the webpack config in PR #62.

Please let me know if there are any problems.

**Comment by neozenith** [comment]
Merged the PR but let’s leave this issue open until we confirm it has been resolved. 

Thanks for spotting and opening the PR

**Comment by neozenith** [comment]
Looks like the events listing is working again. Happy to accept another PR to change to npm ci that actually respects the lock file.
