### ISSUE TITLE
Request for new Meetup to be added to event stream

### ISSUE THREAD

**Issue by BrianHHill** [newwwie/newwwie.com#7]
**Meetup Group URL:** **Meetup relevance:**
https://www.meetup.com/Newcastle-IoT-Pioneers/
Useful for anyone wanting to stay across IoT product ecosystems, integrations, lessons learnt.

**Comment by neozenith** [comment]
@BrianHHill thanks for the contribution! IoT Pioneers is already part of the list.

https://github.com/newwwie/newwwie.com/blob/master/src/js/events/Meetup.js#L275

You can also see the full list of existing meetups. If there are any other on that list we have missed then let us know. 👍 😄
