### ISSUE TITLE
Local development environment requirements

### ISSUE THREAD

**Issue by JayRovacsek** [newwwie/newwwie.com#86]
G'day! 

Currently the project does not describe or provide guidance on the tooling required to contribute or direct a newcomer to how they might assist in the project.
I'd propose we include a simple section within the readme to direct community members towards a starting point for this 😄 

As an extension on this a few OSS efforts to better define and replicate utilised build environments could be leveraged as opt-in for contributors such: is the project open to a changeset that would enable environment replication via docker or nix? (with preference to simplicity and ease-of-use)

**Comment by neozenith** [comment]
This is kind of addressed via dev containers now
