### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by JayRovacsek** [newwwie/newwwie.com#88]
Label says it all - While this adds complexity to the code for newcomers, is the project open to a Typescript conversion?

**Comment by neozenith** [comment]
Yeah open to it. I think there has also been talk about using `bun` over in the Newwwie slack. Open to literally any updates or community lead imporvements. 

There isn't gatekeeping, just very time poor volunteers sorry.

**Comment by adam1658** [comment]
I'll take a crack at this at the /NEW dev sprint
